version: "3"

services:
   tic-tac-toe:
     image: tic-tac-toe:latest
     expose:
       - 8080
     restart: always
     environment:
       VIRTUAL_HOST: tictactoe.nicholasbozentko.com
       LETSENCRYPT_HOST: tictactoe.nicholasbozentko.com
     container_name: tic-tac-toe

networks:
  default:
    external:
      name: nginx-proxy
